### ISSUE TITLE
Update to package with latest Gridstack

### ISSUE THREAD

**Issue by siruscoder** [ckiely91/meteor-gridstack#1]
I would like to use the latest version of gridstack and take advantage of bug fixes, do you know if/when this Atmosphere package would be updated? Thanks for your work!

**Comment by ckiely91** [comment]
Hi @siruscoder, I created this package a while ago when using Atmosphere, though it's now much easier to use packages via NPM. Is there a reason you're unable to do that to get the latest gridstack instead?

**Comment by siruscoder** [comment]
Thanks @ckiely91 for your quick response! I am new to meteor and haven't quite figured out Atmosphere vs npm yet and that might be what I need to do. Thanks again.
